// Source: sinapir_municipios_aderentes(1).xlsx - sheet Municipios SINAPIR.
// Generated from all 375 records; key format: normalized-municipality|UF.
const MUNICIPIOS_SINAPIR = new Set([
  'acrelandia|AC',
  'afonso cunha|MA',
  'aguas lindas de goias|GO',
  'alagoinhas|BA',
  'alcantaras|CE',
  'alcantara|MA',
  'alcinopolis|MS',
  'alfenas|MG',
  'almadina|BA',
  'altaneira|CE',
  'alvorada|RS',
  'amargosa|BA',
  'anajatuba|MA',
  'anapolis|GO',
  'andradina|SP',
  'antonio cardoso|BA',
  'aparecida de goiania|GO',
  'aracaju|SE',
  'aracas|BA',
  'aracatuba|SP',
  'araraquara|SP',
  'araras|SP',
  'araripe|CE',
  'arataca|BA',
  'araucaria|PR',
  'arroio dos ratos|RS',
  'arroio grande|RS',
  'assis brasil|AC',
  'aurelino leal|BA',
  'balneario pinhal|RS',
  'bandeirantes|MS',
  'barbacena|MG',
  'bariri|SP',
  'barra do pirai|RJ',
  'barra do rocha|BA',
  'barra do turvo|SP',
  'barra dos coqueiros|SE',
  'barra mansa|RJ',
  'barretos|SP',
  'barro preto|BA',
  'bataguassu|MS',
  'batatais|SP',
  'bauru|SP',
  'belem|PA',
  'belford roxo|RJ',
  'belmonte|BA',
  'belo horizonte|MG',
  'betim|MG',
  'bom despacho|MG',
  'bom jesus da lapa|BA',
  'boninal|BA',
  'bonito de minas|MG',
  'botucatu|SP',
  'brasileia|AC',
  'britania|GO',
  'brumadinho|MG',
  'buerarema|BA',
  'bujari|AC',
  'bujaru|PA',
  'butia|RS',
  'caatiba|BA',
  'cabo frio|RJ',
  'cachoeira|BA',
  'cachoeirinha|RS',
  'cachoeiro de itapemirim|ES',
  'cafezal do sul|PR',
  'cajazeiras do piaui|PI',
  'camacari|BA',
  'camaca|BA',
  'camamu|BA',
  'camapua|MS',
  'campina grande do sul|PR',
  'campinas|SP',
  'campo azul|MG',
  'campo formoso|BA',
  'campo grande|MS',
  'campo largo|PR',
  'campo magro|PR',
  'canarana|BA',
  'canavieiras|BA',
  'candeias|BA',
  'cantanhede|MA',
  'capixaba|AC',
  'carapicuiba|SP',
  'cariacica|ES',
  'carnaubeira da penha|PE',
  'carneiros|AL',
  'caruaru|PE',
  'casa nova|BA',
  'cascavel|PR',
  'castanhal|PA',
  'castro alves|BA',
  'catu|BA',
  'caxias|MA',
  'cedral|MA',
  'central do maranhao|MA',
  'chapada do norte|MG',
  'chapadinha|MA',
  'coaraci|BA',
  'codo|MA',
  'colombo|PR',
  'conceicao de ipanema|MG',
  'conceicao do mato dentro|MG',
  'concordia|PA',
  'conego marinho|MG',
  'congonhas do norte|MG',
  'congonhas|MG',
  'contagem|MG',
  'corguinho|MS',
  'cornelio procopio|PR',
  'corumba|MS',
  'costa rica|MS',
  'criciuma|SC',
  'cruz das almas|BA',
  'cruzeiro de fortaleza|MG',
  'cruzeiro do sul|AC',
  'cruzeiro|SP',
  'cubatao|SP',
  'cuiaba|MT',
  'curitiba|PR',
  'cururupu|MA',
  'diadema|SP',
  'diamantina|MG',
  'dias d avila|BA',
  'divinopolis|MG',
  'dom joaquim|MG',
  'estancia balnearia de peruibe|SP',
  'eunapolis|BA',
  'feira de santana|BA',
  'firmino alves|BA',
  'floresta azul|BA',
  'florianopolis|SC',
  'foz do iguacu|PR',
  'francisco morato|SP',
  'gandu|BA',
  'gongogi|BA',
  'governador mangabeira|BA',
  'governador valadares|MG',
  'gravata|PE',
  'guaratinga|BA',
  'guarulhos|SP',
  'guimaraes|MA',
  'gurupa|PA',
  'hortolandia|SP',
  'ibicoara|BA',
  'ibicui|BA',
  'ibipeba|BA',
  'ibiracatu|MG',
  'ibirapitanga|BA',
  'ibirataia|BA',
  'icarai de minas|MG',
  'igarape miri|PA',
  'ilheus|BA',
  'independencia|CE',
  'iraquara|BA',
  'irati|PR',
  'iraucuba|CE',
  'itabela|BA',
  'itabira|MG',
  'itabuna|BA',
  'itacare|BA',
  'itagiba|BA',
  'itagimirim|BA',
  'itajai|SC',
  'itaju do colonia|BA',
  'itajuipe|BA',
  'itambe|PE',
  'itapaje|CE',
  'itapebi|BA',
  'itapecuru mirim|MA',
  'itape|BA',
  'itapipoca|CE',
  'itapira|SP',
  'itapitanga|BA',
  'itarantim|BA',
  'itatiba|SP',
  'itororo|BA',
  'itubera|BA',
  'jacarei|SP',
  'jaguaribara|CE',
  'jaiba|MG',
  'januaria|MG',
  'japonvar|MG',
  'jau|SP',
  'jequie|BA',
  'joinville|SC',
  'juazeiro do norte|CE',
  'jucas|CE',
  'juiz de fora|MG',
  'jundiai|SP',
  'jussari|BA',
  'lagarto|SE',
  'lagoa dourada|MG',
  'laranjal do jari|AP',
  'laranjeiras|SE',
  'lauro de freitas|BA',
  'lavras|MG',
  'lencois|BA',
  'lima campos|MA',
  'limeira|SP',
  'limoeiro do norte|CE',
  'londrina|PR',
  'lontra|MG',
  'lorena|SP',
  'macapa|AP',
  'macarani|BA',
  'mage|RJ',
  'maiquinique|BA',
  'manaus|AM',
  'manga|MG',
  'maragogipe|BA',
  'marau|BA',
  'marica|RJ',
  'marilia|SP',
  'maringa|PR',
  'mascote|BA',
  'matao|SP',
  'matias cardoso|MG',
  'matinha|MA',
  'maua|SP',
  'mendes|RJ',
  'mesquita|RJ',
  'minacu|GO',
  'mirandiba|PE',
  'missao velha|CE',
  'monte alegre de sergipe|SE',
  'monte alto|SP',
  'muriae|MG',
  'nilo pecanha|BA',
  'nossa senhora do socorro|SE',
  'nova america|GO',
  'nova ipixuna|PA',
  'nova lima|MG',
  'nova modica|MG',
  'nova russas|CE',
  'novo hamburgo|RS',
  'novos cabrais|RS',
  'oeiras do para|PA',
  'ourem|PA',
  'ouricangas|BA',
  'ouro preto|MG',
  'pacoti|CE',
  'pantano grande|RS',
  'parnarama|MA',
  'passo fundo|RS',
  'pau brasil|BA',
  'pedro do rosario|MA',
  'pelotas|RS',
  'penalva|MA',
  'pereiro|CE',
  'peritoro|MA',
  'piata|BA',
  'pindamonhangaba|SP',
  'pindare mirim|MA',
  'piracicaba|SP',
  'pirai do norte|BA',
  'piraquara|PR',
  'placido de castro|AC',
  'poco das trincheiras|AL',
  'pocos de caldas|MG',
  'pompeu|MG',
  'ponta de pedras|PA',
  'ponta grossa|PR',
  'pontal do parana|PR',
  'ponto chique|MG',
  'porteiras|CE',
  'porto alegre|RS',
  'porto ferreira|SP',
  'porto seguro|BA',
  'porto walter|AC',
  'prado|BA',
  'praia grande|SP',
  'professor jamil|GO',
  'queimadas|BA',
  'querencia|MT',
  'quiterianopolis|CE',
  'regeneracao|PI',
  'registro|SP',
  'riacho da cruz|RN',
  'riacho de santana|BA',
  'ribeirao preto|SP',
  'rio branco|AC',
  'rio claro|SP',
  'rio grande|RS',
  'rochedo|MS',
  'rodrigues alves|AC',
  'rondonopolis|MT',
  'rosario|MA',
  'rubelita|MG',
  'salinas|MG',
  'salitre|CE',
  'salvador|BA',
  'santa barbara do tugurio|MG',
  'santa barbara|BA',
  'santa cruz cabralia|BA',
  'santa cruz da vitoria|BA',
  'santa cruz de goias|GO',
  'santa luzia|BA',
  'santa maria do suacui|MG',
  'santa rita do passa quatro|SP',
  'santa rita|MA',
  'santa rosa do purus|AC',
  'santana|AP',
  'santo amaro da imperatriz|SC',
  'santo amaro das brotas|SE',
  'santo antonio de jesus|BA',
  'santo antonio do rio abaixo|MG',
  'santos|SP',
  'sao bernardo do campo|SP',
  'sao carlos|SP',
  'sao cristovao|SE',
  'sao felix|BA',
  'sao francisco do conde|BA',
  'sao francisco|MG',
  'sao gabriel do oeste|MS',
  'sao gabriel|BA',
  'sao goncalo do abaete|MG',
  'sao joao batista|MA',
  'sao joao da alianca|GO',
  'sao joao das missoes|MG',
  'sao joao do soter|MA',
  'sao jose do divino|MG',
  'sao jose do rio preto|SP',
  'sao jose dos campos|SP',
  'sao luis|MA',
  'sao luiz gonzaga do maranhao|MA',
  'sao miguel do tapuio|PI',
  'sao paulo de olivenca|AM',
  'sao paulo do potengi|RN',
  'sao pedro do suacui|MG',
  'sao raimundo nonato|PI',
  'sao romao|MG',
  'sao tome|RN',
  'sena madureira|AC',
  'senador canedo|GO',
  'senador guiomard|AC',
  'senhora do porto|MG',
  'serra|ES',
  'serrinha|BA',
  'simao dias|SE',
  'sinop|MT',
  'solonopole|CE',
  'sonora|MS',
  'souto soares|BA',
  'tamboril|CE',
  'taua|CE',
  'tenente ananias|RN',
  'toledo|PR',
  'tome acu|PA',
  'trairi|CE',
  'triunfo|PE',
  'tururu|CE',
  'ubaitaba|BA',
  'ubata|BA',
  'uberaba|MG',
  'uberlandia|MG',
  'umarizal|RN',
  'una|BA',
  'uniao dos palmares|AL',
  'uruacu|GO',
  'urucuca|BA',
  'uruguaiana|RS',
  'valparaiso de goias|GO',
  'varzea alegre|CE',
  'varzea grande|MT',
  'varzelandia|MG',
  'vazante|MG',
  'venancio aires|RS',
  'vila bela da santissima trindade|MT',
  'vila velha|ES',
  'virgem da lapa|MG',
  'vitoria da conquista|BA',
  'vitoria|ES',
  'volta redonda|RJ',
  'xapuri|AC',
]);
